---
- hosts: all
  tasks:
  
  - name: load module file for singularity (placeholder)
    shell:
      cmd: module load /root/trial/dep/modules/singularity
  
  - name: run HPL from container
    shell:
      cmd: mpirun -n 8 mpirun --bind-to none --nooversubscribe singularity run --nv /root/trial/dep/hpc-benchmarks:21.4-hpl.sif hpl.sh --cpu-cores-per-rank 8 --cpu-affinity 2-5:6-9:10-13:14-17:24-27:28-31:32-37:38-41 --gpu-affinity 0:1:2:3:4:5:6:7 --dat  ./HPL.dat
